vim.api.nvim_create_user_command("PacmanSync", function()
  require("pacman.ghost").setup()
end, {})
vim.api.nvim_create_user_command("PacmanDash", function()
  require("pacman.maze").open()
end, {})
vim.api.nvim_create_user_command("PacmanDashboard", function()
  require("pacman.maze").open()
end, {})
